<a href="https://colab.research.google.com/github/niteshkumar0205/G-NITESHKUMAR/blob/main/ml_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = [1,2,3,4,5]

arr1 = np.array(a)
b= [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(b)

print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]


In [2]:
print(type(a))
print(type(b))
print(type(arr1))
print(type(arr2))


<class 'list'>
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [4]:
import sys
s = range(1000)

print("size of each elements in list in bytes",sys.getsizeof(s))

print("complete list size in bytes",sys.getsizeof(s)*len(s))

size of each elements in list in bytes 48
complete list size in bytes 48000


In [7]:
import numpy as np

s = np.arange(1000)

print("size of each elements in the list by bytes ",s.itemsize)

print("complete list size in bytes",s.size * s.itemsize)

size of each elements in the list by bytes  8
complete list size in bytes 8000


In [8]:
import time

a = range(1000)
b=range(1000)

start = time.time()

ab = [(a *b) for a,b in zip(a,b)]

end = time.time()

print("total time taken",end - start )

total time taken 0.00020122528076171875


In [14]:
import numpy 
import time

arr1 = np.arange(1000)
arr2 = np.arange(1000)

start = time.time()

arr_mul  = arr1*arr2

end = time.time()

print(" total time taken", end- start)

 total time taken 7.987022399902344e-05


In [15]:
lst1 = [1,2,3,4]

arr = np.array(lst1)

print(arr)

[1 2 3 4]


In [18]:
lst2 = [4,3,2,1]

arr = np.array(lst2)

print(arr)

[4 3 2 1]
