<a href="https://colab.research.google.com/github/niteshkumar0205/G-NITESHKUMAR/blob/main/ml_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = [1,2,3,4,5]

arr1 = np.array(a)
b= [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(b)

print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]


In [2]:
print(type(a))
print(type(b))
print(type(arr1))
print(type(arr2))


<class 'list'>
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [4]:
import sys
s = range(1000)

print("size of each elements in list in bytes",sys.getsizeof(s))

print("complete list size in bytes",sys.getsizeof(s)*len(s))

size of each elements in list in bytes 48
complete list size in bytes 48000


In [6]:
import numpy as np

s = np.arange(1000)

print("size of each elements in the list by bytes ",s.itemsize)

print("compleete list size in bytes",s.size * s.itemsize)

size of each elements in the list by bytes  8
compleete list size in bytes 8000
